### ISSUE TITLE
ALC1150 Front Panel audio crippled 

### ISSUE THREAD

**Issue by ahmadfiroz** [toleda/audio_CloverALC#100]
Rear Panel works well but front panel detects as headphones. But the audio is crippled. Not a hardware issue ( checked in windows )

OS Version : 10.12.3 
Motherboard: z170 pro gaming

**Comment by toleda** [comment]
Crippled means what? Case?

**Comment by ahmadfiroz** [comment]
Distorted . Sounds like grrr.  Grrr. Nzxt h440

**Comment by XWhatevs** [comment]
@ahmadfiroz I have the EXACT same issue. Audio works perfectly if the headphones are plugged in to my case's front panel 3.5mm port, but if they're plugged in directly to my MOBO's 3.5mm jack, the audio is very quiet and crippled/distorted (unusable). @toleda

**Comment by toleda** [comment]
@ahmadfiroz 
z170 pro gaming/macOS does not support the external headphone amplifier. 
Try https://github.com/RehabMan/EAPD-Codec-Commander

**Comment by XWhatevs** [comment]
@toleda I don't think that's the issue, see #101

**Comment by ahmadfiroz** [comment]
Uninstalling Realtek Driver fixed the issue for me . thanks

**Comment by tvhung83** [comment]
@toleda was right, I can fix my front headphone port (ALC3236) using Codec Commander and run 2 commands (following this tutorial: https://www.youtube.com/watch?v=MTbVfRXMJ2I)
```
$ hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x25
$ hda-verb  0x21 SET_UNSOLICITED_ENABLE 0x83
```

**Comment by tvhung83** [comment]
@ahmadfiroz please close ticket if your issue is resolved.
