### ISSUE TITLE
ALC1150 audio works fine on case's 3.5mm jack, very quiet and crippled/distorted when plugged in to the MOBO's 3.5mm jack.

### ISSUE THREAD

**Issue by XWhatevs** [toleda/audio_CloverALC#101]
NOTE: I'm actually using AppleALC , not CloverALC, but vandroiy2013 (the author of AppleALC) said that he's using your resources in his kext and that he's gonna wait for you to fix the bug, then he's gonna update AppleALC.kext (see https://github.com/vit9696/AppleALC/issues/149#issue-218337608)

NOTE: Testing this with headphones which are 100% working (tested them in Windows and on other devices). 

I'm on Sierra (10.12.4), ALC1150, latest version of Clover, and latest versions of AppleALC.kext and Lilu.kext. 

So, the headphones produce perfect audio when they're plugged into the 3.5mm jack that's located on my CASE (in Sys Pref's they recognized as "Headphones"), but if they're plugged into the 3.5mm jack located directly on my motherboard (in Sys Prefs recognized as "Internal Speakers"), they produce pretty quiet and distorted/crippled audio (in other works, totally unusable audio).

I also tested this with my speakers (also 3.5mm). 

Another person here posted the same issue as mine: 

https://github.com/toleda/audio_CloverALC/issues/100

**Comment by toleda** [comment]
Same problem????
His: motherboard sounds good, case not
Yours: case sounds good, motherboard not

Windows is not relevant; no AppleHDA support
Motherboard? Case?

**Comment by XWhatevs** [comment]
@toleda

Sorry, didn't quite catch that. But it seems even more unusual that a mobo wouldn't work and a case would.

MOBO is GA-Z170-D3H and the case is Chieftec BH-02B-B-B

**Comment by toleda** [comment]
Motherboard manufacturers are trying to differentiate on audio performance, a completely subjective attribute, no winners.  Your motherboard has no external amps. Try 2nd Line Out/Black connector.

**Comment by XWhatevs** [comment]
@toleda 2nd Line Out works fine. Though I have no idea what you said means. 

Also, another important point is that audio worked on ALL ports (green, black, etc.) before I installed Windows (10) on my hackintosh. After installing it, audio on the green port stopped working. #100 also mentioned that he has Windows installed, so that may really have an effect.

**Comment by toleda** [comment]
Documented. Choices:
1. Uninstall Realtek driver, use Windows driver
2. Cold boot macOS

**Comment by ahmadfiroz** [comment]
Uninstalling Realtek Driver fixed the issue for me . thanks

**Comment by barrrrt** [comment]
I had the same issue. Uninstalling the driver in Windows is one option, but the best solution for me was to install the CodecCommander.kext. 
If you use Clover, you can just put it in the KEXT Folder of the clover folder.
