### ISSUE TITLE
No audio devices, ALC898

### ISSUE THREAD

**Issue by anonymous83** [toleda/audio_CloverALC#110]
Everything was working perfectly until there was the update to 10.11.6

I've tried that a clean install of macOS 10.12.4 and the same issue occurs.

Currently I have no DSDT Fixes, Rt Variables are set to BooterConfig: 0x28, CsrActiveConfig: 0x67, Audio ID: 1

Terminal output attached
[terminal output.zip](https://github.com/toleda/audio_CloverALC/files/968752/terminal.output.zip)

Can you help me Toleda?

**Comment by toleda** [comment]
config.plist is damaged, attach.

**Comment by anonymous83** [comment]
Thanks for your quick reply
Config.plist in attachment

[config.plist.zip](https://github.com/toleda/audio_CloverALC/files/969021/config.plist.zip)

**Comment by anonymous83** [comment]
Managed to solve it.
Just trashed my config.plist and rebuilt one from scratch. all issues were sorted.

Many thanks for your guidance and help. spot on
