### ISSUE TITLE
"No output devices found" - ALC892

### ISSUE THREAD

**Issue by krnsripati** [toleda/audio_CloverALC#111]
**1. Description of audio problem**
System Preference > Sound > Output - "No output devices found"
![image](https://cloud.githubusercontent.com/assets/856090/25596139/521818d0-2ee5-11e7-8145-56e3a1200339.png)

**2. OS X version/motherboard model/BIOS version/processor/graphics**
10.12.4/P8P67 Pro Rev 3.0/3602/i7 2600k/ATI Radeon Dual-X R9 270X 2GB

**3. Procedure/Guide used**
Previously audio worked correctly for 10.12.4, but due to some hard disk crash, I reinstalled from scratch using MultiBeast
![image](https://cloud.githubusercontent.com/assets/856090/25596364/5a2df4bc-2ee6-11e7-9ae9-ce75271fbf88.png)
For audio run command - audio_cloverALC-120_v1.0f1.command.

**4. Terminal/Shell/File/Export Text As. . . (if run)**
[Terminal Output.zip](https://github.com/toleda/audio_CloverALC/files/968879/Terminal.Output.zip)

**5. Copy of IOReg - IOReg_v2.1/File/Save a Copy As…, verify file (Tools 1.)**
[Kirankumar’s iMac.ioreg.zip](https://github.com/toleda/audio_CloverALC/files/968882/Kirankumar.s.iMac.ioreg.zip)

**6. Copy Of Console/All Messages (last boot)/File/Save a Copy As..**
[Console.txt](https://github.com/toleda/audio_CloverALC/files/968889/Console.txt)

**7. Installed S/L/E/AppleHDA.kext or AppleHDA8Series AppleHDAxxx kext**
[AppleHDA.kext.zip](https://github.com/toleda/audio_CloverALC/files/968890/AppleHDA.kext.zip)

**8. Screenshot:**
   1. DPCIManager/Status (Tools 2.)
   ![image](https://cloud.githubusercontent.com/assets/856090/25596679/09dec8b8-2ee8-11e7-92ba-4d9209581dca.png)

  2. System Information/Hardware/Audio/Intel High Definition Audio (not Devices)
  ![image](https://cloud.githubusercontent.com/assets/856090/25596702/277721d6-2ee8-11e7-80dd-c80a6c4dfcea.png)

**11. Clover (if installed)**
  1. EFI/CLOVER/config.plist
  [config.plist.zip](https://github.com/toleda/audio_CloverALC/files/968899/config.plist.zip)

  2. DPCIManager/Misc/Boot Log (Tools 2.)
  [DPCIManager-Boot-Log.txt](https://github.com/toleda/audio_CloverALC/files/968902/DPCIManager-Boot-Log.txt)

  EFI - [EFI.zip](https://github.com/toleda/audio_CloverALC/files/968903/EFI.zip)

I hope this will help you in debugging. Thanks in Advance.

**Comment by toleda** [comment]
Did everything correctly. Bad news, Asus P67 3xxx BIOS disables macOS audio.  Only known fix is downgrade BIOS to 2xxx. HDMI audio is likely to work, if interested.

**Comment by krnsripati** [comment]
I downgraded to 2xxx. Now audio working like a charm, just by running MultiBeast ALC892. Thanks a lot, Toleda.

**Comment by Krazubu** [comment]
Hey, I finally found the solution :
https://www.insanelymac.com/forum/topic/276380-the-inevitable-p8p67-pro-install-guide/?do=findComment&comment=2657616

**Comment by toleda** [comment]
Great work, thanks for posting the solution.
