### ISSUE TITLE
Really low volume on ALC1150 10.12.5

### ISSUE THREAD

**Issue by cydia2020** [toleda/audio_CloverALC#113]
All the things are working except the volume is really small, it's like 2% volume enabled in Windows, any ideas?

Thanks

**Comment by cydia2020** [comment]
https://www.tonymacx86.com/threads/audio-issues-alc1150-on-sierra.210894/ like this in post no.4

**Comment by toleda** [comment]
Motherboard?

**Comment by cydia2020** [comment]
Solved by using CodecCommander, thanks for helping, I will close it now
