### ISSUE TITLE
No Audio Devices ALC1150 / macOS 10.13.2 

### ISSUE THREAD

**Issue by johnryan** [toleda/audio_CloverALC#130]
BooterConfig: 0x28, CsrActiveConfig: 0x67

```
EFI partition is mounted
System Integrity Protection status: disabled.

OK to patch
Confirm Realtek ALC1150 (y/n): y
Clover Audio ID Injection (y/n): y
Use Audio ID: 1 (y/n): y

Download ALC1150 files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23555  100 23555    0     0  43573      0 --:--:-- --:--:-- --:--:-- 43620
Edit config.plist/Devices/Audio/Inject/1
Edit config.plist/SystemParameters/InjectKexts/YES
Download kext patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1742  100  1742    0     0   2066      0 --:--:-- --:--:-- --:--:--  2066
Download config kext and install ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4223  100  4223    0     0  35669      0 --:--:-- --:--:-- --:--:-- 35788
Install /Volumes/EFI/EFI/CLOVER/kexts/10.13/realtekALC.kext
Install System/Library/Extensions/AppleHDA.kext/ALC1150 zml files
Fix permissions ...
Kernel cache...
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84ddbd340 [0x7fffa9d46980]> { URL = "FakeSMC.kext/ -- file:///Library/Extensions/", ID = "org.netkas.driver.FakeSMC" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84ddb8650 [0x7fffa9d46980]> { URL = "FakeSMC_CPUSensors.kext/ -- file:///Library/Extensions/", ID = "org.hwsensors.driver.CPUSensors" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84ddb7670 [0x7fffa9d46980]> { URL = "FakeSMC_GPUSensors.kext/ -- file:///Library/Extensions/", ID = "org.hwsensors.driver.GPUSensors" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84dd5ba20 [0x7fffa9d46980]> { URL = "FakeSMC_ACPISensors.kext/ -- file:///Library/Extensions/", ID = "org.hwsensors.driver.ACPISensors" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84dcd44a0 [0x7fffa9d46980]> { URL = "USBInjectAll.kext/ -- file:///Library/Extensions/", ID = "com.rehabman.driver.USBInjectAll" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84dc9e540 [0x7fffa9d46980]> { URL = "AppleIntelE1000e.kext/ -- file:///Library/Extensions/", ID = "com.insanelymac.driver.AppleIntelE1000e" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84dc79950 [0x7fffa9d46980]> { URL = "FakeSMC_LPCSensors.kext/ -- file:///Library/Extensions/", ID = "org.hwsensors.driver.LPCSensors" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84dc6d600 [0x7fffa9d46980]> { URL = "SmashEnabler.kext/ -- file:///Library/Extensions/", ID = "io.github.jackoalan.SmashEnabler" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84db038b0 [0x7fffa9d46980]> { URL = "FakeSMCKeyStore.kext/ -- file:///System/Library/Extensions/FakeSMC.kext/Contents/PlugIns/", ID = "org.hwsensors.driver.FakeSMCKeyStore" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7ff84da21310 [0x7fffa9d46980]> { URL = "AppleHDA.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.driver.AppleHDA" }
kext file:///System/Library/Extensions/UAFWAudio.kext/ is in hash exception list, allowing to load
Kext with invalid signatured (-67013) allowed: <OSKext 0x7ff84c40d570 [0x7fffa9d46980]> { URL = "AppleDataSetManagement.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.AppleDataSetManagement" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff84a63c2f0 [0x7fffa9d46980]> { URL = "CodecCommander.kext/ -- file:///System/Library/Extensions/", ID = "org.tw.CodecCommander" }
kext file:///System/Library/Extensions/UAFWAudio.kext/ is in hash exception list, allowing to load
KernelCache ID: 883B238A78A12CA5F9626AB013520C6A
kextcache updated critical boot files, requesting launchd reboot

Install finished, restart required.
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

After completion i run `sudo kextcache -i /` (to prevent the hang on reboot) then reboot. Is there anything that seems wrong here? Everything worked fine until High Sierra

**Comment by toleda** [comment]
See https://github.com/toleda/audio_ALC_guides/blob/master/Problem%20Reporting.md
Attach requested files.

**Comment by johnryan** [comment]
@toleda Sorry about that, attached a zip. One thing to note is that oddly there were 3 SSDT-related files in the /patched folder (i attached all 3)
[Audio Files.zip](https://github.com/toleda/audio_CloverALC/files/1656733/Audio.Files.zip)

**Comment by toleda** [comment]
Motherboard?

**Comment by johnryan** [comment]
Motherboard: gigabyte z97x-ud7 th
Graphics: NVIDIA GeForce GTX 760 4 GB

**Comment by toleda** [comment]
Issues:
Same kexts in 3 or more places; 10.13, Other, /L/E:
CodecCommander in /L/E only, remove from /S/L/E, /Other and /10.13
FakeSMC in /Other only
All other kexts in /Other only
Remove Lilu, RealtekRTL8111, ALXEthernet and duplicates
Restart and reply with new files

RampageDev: ssdt and ssdt-1
No: CPU PM/GPU PM/audio
What is the benefit?

MultiBeast: SSDT-SB-i7, not for your processor

**Comment by johnryan** [comment]
@toleda Most of those kexts are just copied over from years ago before I started using multibeast. Is it safe to just remove them all from 10.13/Other and re-run MultiBeast? Not sure the best way to get a "clean slate"

RE: RampageDev ssdt's...these are pretty old and i copied them a few years ago from a tutorial. Would you recommend deleting these and letting MultiBeast re-add a clean one?

Thanks for the help!

**Comment by toleda** [comment]
Make bootable backup and CLOVER backup.
Remove the ssdts
Install:
https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-1-with_ioreg:hdef.zip
https://github.com/toleda/audio_hdmi_9series/blob/master/ssdt_lpc/ssdt_lpcb-9series.zip
https://github.com/toleda/audio_hdmi_9series/blob/master/ssdt_xcpm/ssdt_xcpm.zip
https://github.com/toleda/audio_hdmi_amd-nvidia/blob/master/ssdt_hdmi-nvidia/ssdt_hdmi-nvidia-PEG0.zip
Not sure how wifi is enabled
Restart, reply with new files

**Comment by johnryan** [comment]
@toleda attached new files. I installed all the .amls from above but same result, one thing of note it *seems* like MultiBeast re-adds the FakeSMC to L/E and S/L/E. But I removed the other kexts.

Any suggestions would be appreciated!

[Audio Files 2.zip](https://github.com/toleda/audio_CloverALC/files/1658278/Audio.Files.2.zip)

**Comment by toleda** [comment]
CPU PM, GPU PM working
See nothing wrong with audio
run cloverALC, reply with new files
Note, if you just updated to 10.13.3, do not run cloverALC yet,

**Comment by johnryan** [comment]
@toleda these files are after I already ran cloverALC. I'm still on 10.13.2. One thing i've been doing after cloverALC is `sudo kextcache -i /` would that cause any problems?

**Comment by johnryan** [comment]
update...tried without running `kextcache` before restart but same result. No audio device detected by macOS

**Comment by johnryan** [comment]
update # 2 ...After re-adding the Lilo and AppleALC kexts the audio device is now detected on startup!...However after the computer goes to sleep the sound stops working (though the device is at least still detected, just no sound). I was under the impression that CodedCommander.kext was supposed to take care of waking the sound card back up. Is this a known issue?

**Comment by johnryan** [comment]
update # 3...solved...I re-enabled power nap and switched the output (and speaker connection) from "Internal Speakers" to "Line Out". After making those changes everything seems to be working. Thanks for the guidance!
