### ISSUE TITLE
it works, but when i switch back from my USB-Headset it's "dead"

### ISSUE THREAD

**Issue by riotm0de** [toleda/audio_CloverALC#131]
Hi,

thanks for the kext - it works here with HighSierra.

but when i switch back my Audio-Output from USB-Headset to internal-output it wont play music again on my 3,5mm-Jack Soundsystem - on my USB devices its playing fine , but not on my 3,5-Jack 

how can i fix this ? thanks

**Comment by toleda** [comment]
No idea, a few details would be useful.
motherboard, codec, USB version, IOReg, etc.

**Comment by riotm0de** [comment]
thanks for reply and sorry - its:

Codec: ALC887
MoBo: GA-Z77-DS3H
High Sierra 10.13.3
ID: 1

when i switch from internal audio to my G933 Headset (USB Dongle) and go back to internal audio -  i have no sound, when i close all my apps, especially Chrome, it starts a few sec. or minutes later again... 
but its frustrating without sound in these minutes 

thank you

**Comment by toleda** [comment]
"no problems in yosemite for 3 years"
What changed?

**Comment by riotm0de** [comment]
i was using (your) AppleHDA.kext and HDAEnabler5.kext

**Comment by toleda** [comment]
AppleALC/Audio ID: 5 is not my work. 
Remove HDAEnabler5.kext

Use Audio ID: 1 for 2 inputs/1 output
Audio ID: 2 for 0 inputs/3 outputs (5.1)

Clover: set config.plist/Devices/Audio/Inject/1 or 2
No Clover: https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-1-with_ioreg:hdef.zip or
https://github.com/toleda/audio_ALCInjection/blob/master/ssdt_hdef/ssdt_hdef-2-with_ioreg:hdef.zip

**Comment by riotm0de** [comment]
hey toleda, thanks for reply!

I do not use HDAEnabler5.kext in High Sierra - i installed a clean HighSierra with Clover 
(in yosemite i used HDAEnabler and that worked without any problems, but does not in High Sierra)

so now in High Sierra i am using your Patch.command and used AudioID 1 on a clean HS install
in Clover i set Inject to 1 in config.plist - then i get audio, but with "bugs" ... 

like now - i listened to music and i dunno why, but minutes later i have no audio , and dunno how to get it back - i need just do wait some minutes and it will come back again... 

but this is super frustrating....  any ideas ? 

my USB-Microphone  with Audio-Output plays music without any problems ... 
but i want to connect the audio-jack to my OnBoard Port

**Comment by toleda** [comment]
Attach config.plist and a copy Of IOReg.

**Comment by riotm0de** [comment]
here you have:
[Archiv.zip](https://github.com/toleda/audio_CloverALC/files/1746913/Archiv.zip)

thank you for looking into it!

**Comment by toleda** [comment]
Try config.plist/Devices/Audio/:
AFGLowPowerState/NO
ResetHDA/NO

Reply with IOReg, config.plist and Clover boot log.

**Comment by riotm0de** [comment]
thanks toleda! - i looks like the issue is gone now! 

THANKS!
