### ISSUE TITLE
892 How to install and drive? 

### ISSUE THREAD

**Issue by Beipy** [toleda/audio_CloverALC#141]
My motherboard is B250m.
The system I installed was 10.13.6.
The current driver, Apple ALC.kext, is not the perfect driver to use, only one output.
![qq20180811-211040](https://user-images.githubusercontent.com/33574750/43998457-0cb36a20-9dab-11e8-99c1-e0ae657b11bc.png)

**Comment by toleda** [comment]
MSI B250M Gaming Pro is 887, not 892
What audio ID?
Attach IOReg and config.plist.

**Comment by Beipy** [comment]
It has been solved.
