### ISSUE TITLE
Add Support for ALC668

### ISSUE THREAD

**Issue by pacificfils** [toleda/audio_CloverALC#18]
Hello,

I would like to have support for the ALC668 AppleHDA patch. I have a copy of a working KEXT if you want it. This doesn't have to be high-priority, but it would be a great addition, as well as other ALC cards.

Thanks!

[[[ Requesting tag feature-request ]]]

**Comment by toleda** [comment]
Sorry, I simply cannot support kexts that I do not own.  If you have working files, you can adapt this method to your codec.  For details on the method, see README credit links.
