### ISSUE TITLE
./audio_cloverALC-100.sh: line 621: [: =: unary operator expected

### ISSUE THREAD

**Issue by ilanbiala** [toleda/audio_CloverALC#19]
`./audio_cloverALC-100.sh: line 621: [: =: unary operator expected`

**Comment by toleda** [comment]
Reply with Terminal Saved Output:
Terminal/Shell/Export Test As...

**Comment by ilanbiala** [comment]
@toleda it bricked my computer into an infinite restart loop, so I probably won't be able to get that info for you.

**Comment by toleda** [comment]
Quit Terminal.

**Comment by ilanbiala** [comment]
I can't even get into the OS.

**Comment by toleda** [comment]
At the point the error occurred, audio success had not been validated. No system files were touched.  Your boot problem has nothing to do with the script.

**Comment by ilanbiala** [comment]
I had already restarted my computer 10-15 times. That time, all I did was log in, run the shell script, quit Terminal, and then restart. Then I got into an infinite restart loop.

**Comment by toleda** [comment]
Did you get the "unary operator expected" error?

**Comment by ilanbiala** [comment]
Yes that is why I created this issue...
