### ISSUE TITLE
Support for ALC662v2

### ISSUE THREAD

**Issue by rchovan** [toleda/audio_CloverALC#23]
Hi, 
could you please add support for ALC662v2 (MB Asrock 4core1600-GLAN)
![alc662v2](https://cloud.githubusercontent.com/assets/6713920/6563989/8ed0a6f2-c6a5-11e4-93e9-2abd209c985c.jpg)

**Comment by toleda** [comment]
I can only support codecs I own.

**Comment by rchovan** [comment]
Is there a way how I can extract required informations from my sound card
for you?
Dňa 21.3.2015 0:55 používateľ "toleda" <notifications@github.com> napísal:

**Comment by toleda** [comment]
Apologies, see previous reply.
