### ISSUE TITLE
ALC887 audio lag

### ISSUE THREAD

**Issue by rhacker** [toleda/audio_CloverALC#24]
I have experienced a big lag in sound when playing csgo. I don't know if this is the problem of the kext, or game. The sound is much more responsive in Windows.

Thanks for your great work :)

**Comment by toleda** [comment]
Never played csgo.  Suggest you try it with a native Mac.  Not one line code in AppleHDA changes with the script.

**Comment by rhacker** [comment]
Thanks for the response .
