### ISSUE TITLE
ALC 888 not working

### ISSUE THREAD

**Issue by litan1106** [toleda/audio_CloverALC#25]
I just installed a native AppleHDA.kext before I ran that command.

Print: Entry, ":CFBundleShortVersionString", Does Not Exist
Error occurred, no S/L/E/AppleHDA.kext installed
No system files were changed

**Comment by toleda** [comment]
Where did you get the native AppleHDA.kext?

**Comment by litan1106** [comment]
I reinstalled Yosemite and fixed it. Thanks. ALC888 Legacy is working :dancer
