### ISSUE TITLE
Is ALC888S-VD a special model ?

### ISSUE THREAD

**Issue by allenwq** [toleda/audio_CloverALC#28]
I've tried this on my ECS Q45-AM mobo, but no lucky:

Device shows in the list and showed that it's "ALC88S-VD", but I cannot hear any sound and also cannot select output/input devices in system preferences.

**Comment by toleda** [comment]
Device_id and revision? Use IOReg, IOJones or DPCIManager

**Comment by allenwq** [comment]
![screen shot 2015-03-28 at 9 26 06 am](https://cloud.githubusercontent.com/assets/4983239/6879326/3badd21a-d52d-11e4-8b9c-64a7ffb7ce30.png)

@toleda  This is the screen shot from DPCIManager, Thanks for helping !

**Comment by allenwq** [comment]
Installation log:
```

rtition mounted, Finder/Devices/EFI
EFI partition is mounted
Confirm Realtek ALC888 (y/n): y
ALC888 v_0x100202 (Legacy)
Clover Audio ID Injection (y/n): y
Use Audio ID: 1 (y/n): y

Download ALC888 files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23970  100 23970    0     0   9754      0  0:00:02  0:00:02 --:--:--  9755
Edit config.plist/Devices/Audio/Inject/1
Edit config.plist/SystemParameters/InjectKexts/YES
Edit config.plist/Boot/Arguments/kext-dev-mode=1
Download kext patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1335  100  1335    0     0    734      0  0:00:01  0:00:01 --:--:--   734
Print: Entry, ":KernelAndKextPatches:KextsToPatch:", Does Not Exist
Edit config.plist: Add KernelAndKextPatches/KextsToPatch - Fixed
Install /Volumes/EFI/EFI/CLOVER///kexts/10.10/realtekALC.kext
Download config kext and install ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3451  100  3451    0     0   1923      0  0:00:01  0:00:01 --:--:--  1922
Install System/Library/Extensions/AppleHDA.kext/ALC888 zml files
Fix permissions ...
Kernel cache...
rebuilding //System/Library/Caches/com.apple.kext.caches/Startup/kernelcache
IOBluetoothHostControllerUARTTransport.kext has no Info.plist file.
IOBluetoothHostControllerUARTTransport.kext has no Info.plist file.
IOBluetoothHostControllerUARTTransport.kext has no Info.plist file.
IOBluetoothHostControllerUARTTransport.kext has no Info.plist file.
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext msdosfs.kext
kext net.osx86.kexts.GenericUSBXHCI  102081009 is in exception list, allowing to load
kext org.hwsensors.driver.LPCSensors  136400009000 is in exception list, allowing to load
kext org.hwsensors.driver.GPUSensors  136400009000 is in exception list, allowing to load
kext org.hwsensors.driver.CPUSensors  136400009000 is in exception list, allowing to load
kext org.hwsensors.driver.ACPISensors  136400009000 is in exception list, allowing to load
kext org.netkas.driver.FakeSMC  136400009000 is in exception list, allowing to load
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleKextExcludeList.kext
kext com.insanelymac.driver.AppleIntelE1000e  301009000 is in exception list, allowing to load
kext-dev-mode allowing invalid signature -67054 0xFFFFFFFFFFFEFA12 for kext AppleHDA.kext

Install finished, restart required.
To save a Copy to this Terminal session: Terminal/Shell/Export Text As ...
logout
 
```

**Comment by toleda** [comment]
Script ran successfully.  Audio devices?  Sound?

**Comment by allenwq** [comment]
Tried for few days and ends up with a voodoohda (not working well though) ><

Thanks for helping.

**Comment by ser912** [comment]
Hi! I have the same realtek alc888s-vd codec. (But audit 0х0001).
OS Sierra works well, except a sound.
Attempt to correct by your method (a script of audio_cloverALC-120.command.zip) didn't leave. Audio ID=1 in Clover. Any council. Thanks (Excuse for my bad English)
![2016-09-25 21 18 25](https://cloud.githubusercontent.com/assets/22432678/18817282/a8f32342-8365-11e6-87b4-3881ad42c420.png)

**Comment by ser912** [comment]
Hi! I have the same realtek alc888s-vd codec. (But audit 0х0001).
OS Sierra works well, except a sound.
Attempt to correct by your method (a script of audio_cloverALC-120.command.zip) didn't leave. Audio ID=1 in Clover. Any council. Thanks (Excuse for my bad English)
![2016-09-25 21 18 25](https://cloud.githubusercontent.com/assets/22432678/18817287/c109fc4e-8365-11e6-81e7-e3bfe63e06a3.png)

**Comment by ser912** [comment]
Hi! I have the same realtek alc888s-vd codec. (But audit 0х0001).
OS Sierra works well, except a sound.
Attempt to correct by your method (a script of audio_cloverALC-120.command.zip) didn't leave. Audio ID=1 in Clover. Any council. Thanks (Excuse for my bad English)
![2016-09-25 21 18 25](https://cloud.githubusercontent.com/assets/22432678/18817294/d6a82a58-8365-11e6-9ad4-952918d345bf.png)

**Comment by ser912** [comment]
![2016-09-25 21 21 34](https://cloud.githubusercontent.com/assets/22432678/18817312/1871e758-8366-11e6-81ba-db84c939e6b0.png)

**Comment by ser912** [comment]
![2016-09-25 21 25 52](https://cloud.githubusercontent.com/assets/22432678/18817345/b22b6b4e-8366-11e6-82c4-a45e4b9c21ec.png)
