### ISSUE TITLE
ALC 283 Acer E5-571G

### ISSUE THREAD

**Issue by NyanSatan** [toleda/audio_CloverALC#39]
Hello everyone. I have a problem with ALC 283 audio on Acer E5-571G. Internal speaker works very good, but not the headphones. In headphones I have distortions, and periodically missing low and middle frequencies. I use one of the latest Clover and Audio_ID 1 (injecting via Clover). Please help. 
Best wishes, Ivan from Russia

**Comment by NyanSatan** [comment]
OS X 10.9.5

**Comment by NyanSatan** [comment]
And what is interesting, sound in speakers connected by headphones port is OK too, but not in the headphones

**Comment by toleda** [comment]
Off topic. The ALC283 from this repo only supports NUC and BRIX PRO, no laptops.
