### ISSUE TITLE
ALC892 - no sound over digital output

### ISSUE THREAD

**Issue by cristiansavaro** [toleda/audio_CloverALC#51]
Hi,

I have the GA-B85-HD3 (rev. 1.x) board which features the Realtek ALC892 codec. The analog out is working fine but digital out is working only under windows. Your script ran just fine under my mavericks install. After that I just found a bunch of literature to fix the issue but i wasn't really able to apply the modifications as instructed in the pdf on point 7. can you help me out on private toleda ?

**Comment by cristiansavaro** [comment]
i just found a bunch of literature to fix the issue but i wasn't really able to apply the modifications as instructed in the pdf on point 7. can you help me out ?

**Comment by toleda** [comment]
Does the optical cable have a signal, red light? What application?
Which .pdf/point 7?

**Comment by cristiansavaro** [comment]
This is what i am referring to, quoting from your pdf:

7. Substitute SPDIF-2 Wire Output: Replaces SPDIFOut Optical with motherboard
SPDIF 2 wire SPDIF audio output device

A. Edit Platforms.xml/zml
1. Open Item/PathMapID
2. Open the current SPDIFOut (last item)
3. Edit this path map as follows:
4. Current:
? Item 0/NodeID/Number/30
? Item 1/NodeID/Number/6
5. New:
? Item 0/NodeID/Number/17
? Item 1/NodeID/Number/16

B. Edit HDAHardwareConfigDriver/info.plist or realtekALC/Info.plist
1. Open Item/CodecID
2. Verify CodecID/LayoutID
3. Edit ConfigData (1150 only, edit each entry, 21 to 01)
? Find: 21171cf0 21171d00 21171e00 21171f40
? Replace: 21171ca0 21171d01 21171e43 21171f99
? Find: 21e71c90 21e71d61 21e71e4b 21e71f01
? Replace: 21e71cf0 21e71d00 21e71e00 21e71f40
C. Save, install and restart

1. I am not 100% sure that @A i managed to edit the right thing.
2. I didn't find the patterns @B at all (i am running mavericks. does that count ?)

**Comment by toleda** [comment]
OK. 
@A: what PathMapID did you edit?
@B: Are editing a patched AppleHDA.kext or the realtekALC.kext?
Post files to file sharing service and reply with link.

**Comment by cristiansavaro** [comment]
I gave up and bought a mac compatible pci-e sound card.
