### ISSUE TITLE
[ALC892] Unexpected end of file

### ISSUE THREAD

**Issue by PhilRiver** [toleda/audio_CloverALC#55]
When running the script for ALC892

OK to patch
Confirm Realtek ALC892 (y/n): y
./audio_cloverALC-110.sh: line 1422: syntax error: unexpected end of file

**Comment by Daniesy** [comment]
I have this problem too, but for ALC888

**Comment by RayG210** [comment]
Also having the same issue, ALC1150.

**Comment by toleda** [comment]
Apologies, fixed. Note, Deprecated folder always stores previous working version.

**Comment by PhilRiver** [comment]
Nice! Thanks a lot!
