### ISSUE TITLE
Digital SPDIF-OUT

### ISSUE THREAD

**Issue by trimal2** [toleda/audio_CloverALC#7]
Is it possible to get Digital SPDIF-OUT working on ALC887?

**Comment by stefarossi** [comment]
I'm having problems applying "Procedure 7. Substitute SPDIF-2 Wire Output" to my kext. I have an ALC892.

As far as I can tell, I should have Audio ID: 1 and PathMapId: 45.

This is the output of audio_codecdetect_v1.6.command:
```
$ ./audio_codecdetect_v1.6.command 
File: audio_codecdetect.command_v1.6

HDMI audio codec(s)

Onboard audio codec
Realtek: 0x10ec0892

OS X/10.11.5 Onboard Audio
Device: HDEF@1B
Audio ID: 1

Valid audio codec, audio device and Audio ID; audio injection is working
Finished
```

I don't really know what to modify in Platforms.xml.zlib. I was able to inflate it, edit it, deflate it and place it back, but nothing changed. Can you please help me?

**Comment by toleda** [comment]
PathMapID 45 is not correct. See Appendix B of the customization guide; use PathMapID 892.

**Comment by stefarossi** [comment]
Thanks to your suggestion I was able to get it to work, thank you so much!
