### ISSUE TITLE
Audio Lag, Stuttering, Distortion

### ISSUE THREAD

**Issue by Tsume** [toleda/audio_CloverALC#77]
I'm not sure if this is a codec issue or what. But figured this would be the best place to look. After continuous use, the audio starts getting progressively distorted. After a while there's noticeable lag that accompanies the distortion. Any clue on how to fix this? Using ALC887, I'm new to this, so if I need to include anything let me know.

**Comment by toleda** [comment]
Are you using Clover bootloader.  If yes, attach config.plist.

**Comment by Tsume** [comment]
Yes, I am using Clover bootloader. My config.plist is below. I hope.

[config.plist.txt](https://github.com/toleda/audio_CloverALC/files/368173/config.plist.txt)

**Comment by toleda** [comment]
If config.plist/CPU/UseARTFrequency or FrequencyMHz were set, that would cause an audio problem described.  No other ideas.

**Comment by Tsume** [comment]
Thanks for the tip. I updated to Clover v3423, then used clover configurator to toggle UseARTFrequency. The issue seems to have gone away. Always occured around the 2 minute mark when playing music. On the 3rd song and no distortion yet. It be worth noting for any future googlers/searchers. I had an Overclock before. I reset the OC, prior to updating Clover and toggling UseARTFreq setting.

**Comment by sandyplus** [comment]
I encountered the same issue. After a few minutes of music playing, the sound started to become wired.
