### ISSUE TITLE
10.12 ALC892 can not sound

### ISSUE THREAD

**Issue by maboloshi** [toleda/audio_CloverALC#78]
1.
“System Preferences”—>Sound—>Output
can list the output devices, But any output device can not sound

2.
Version: OS X 10.12 Beta (16A254g) 
Motherboard: ASRock B75M-ITX
 BIOS: Patched 1.80
 Processor: i3-3225
 Graphics: Intel HD Graphics 4000 1536 MB

4.
shamozhzideMini:~ maboloshi$ /Users/maboloshi/Downloads/audio_codecdetect_v1.6.command 
File: audio_codecdetect.command_v1.6
OS X Version: 10.12 is not supported
No system files were changed
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...

5.
[5.IOReg_output.txt](https://github.com/toleda/audio_CloverALC/files/380066/5.IOReg_output.txt)

6.
[system.log.zip](https://github.com/toleda/audio_CloverALC/files/380085/system.log.zip)

7.
[AppleHDA.kext.zip](https://github.com/toleda/audio_CloverALC/files/380067/AppleHDA.kext.zip)

8.
![snip20160724_1](https://cloud.githubusercontent.com/assets/7850715/17081444/5cdbc4f2-518b-11e6-9efb-d8be86247dc9.png)
![snip20160724_2](https://cloud.githubusercontent.com/assets/7850715/17081446/5df6f456-518b-11e6-96f0-5ffb60b119f6.png)
![snip20160724_3](https://cloud.githubusercontent.com/assets/7850715/17081445/5d14b78a-518b-11e6-9565-9e241bcb819a.png)

9. 

run audio_cloverALC-120_v1.0a0.command

==============
Last login: Sat Jul 23 21:59:58 on console
Restored session: 2016年 7月23日 星期六 17时34分53秒 CST
shamozhizideMac-mini:~ maboloshi$ /Users/maboloshi/Downloads/audio_cloverALC-120_v1.0a0.command 
 
Agreement
The audio_cloverALC-120 script is for personal use only. Do not distribute
the patch, any or all of the files or the resulting patched AppleHDA.kext
for any reason without permission. The audio_cloverALC-120 script is
provided as is and without any kind of warranty.
 
File: audio_cloverALC-120.command_v1.0a0
Release Mode
Password:
Sorry, try again.
Password:
EFI partition is mounted
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

OK to patch
Confirm Realtek ALC892 (y/n): y
Clover Audio ID Injection (y/n): y
Use Audio ID: 3 (y/n): y

Download ALC892 files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25585  100 25585    0     0   3041      0  0:00:08  0:00:08 --:--:--  3041
Edit config.plist/Devices/Audio/Inject/3
Edit config.plist/SystemParameters/InjectKexts/YES
Download kext patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1418  100  1418    0     0    183      0  0:00:07  0:00:07 --:--:--   183
Download config kext and install ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3665  100  3665    0     0    471      0  0:00:07  0:00:07 --:--:--   471
Install /Volumes/EFI/EFI/CLOVER/kexts/10.12/realtekALC.kext
Install System/Library/Extensions/AppleHDA.kext/ALC892 zml files
Fix permissions ...
Kernel cache...
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext RealtekRTL8111.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASRAID2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASHBA2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOCelerityFC8.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext LPCSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext GPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ACPISensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakeSMC.kext
kext-dev-mode allowing invalid signature -67054 0xFFFFFFFFFFFEFA12 for kext AppleHDA.kext
KernelCache ID: C38E5387B7751823541CFECCBE8191C9
symlink("/System/Library/PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 17 (File exists) <createPrelinkedKernel 2795>
kextcache updated critical boot files, requesting launchd reboot

Install finished, restart required.
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...
=====================

11.Clover
[B75M-ITX.zip](https://github.com/toleda/audio_CloverALC/files/380063/B75M-ITX.zip)
[bootlog.log.txt](https://github.com/toleda/audio_CloverALC/files/380064/bootlog.log.txt)

**Comment by toleda** [comment]
Apologies for the delay.
Issue:
KernelCache ID: C38E5387B7751823541CFECCBE8191C9
symlink("/System/Library/PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 17 (File exists)

Not audio, system problem.

**Comment by maboloshi** [comment]
I try 
 rm /System/Library/Caches/com.apple.kext.caches/Startup/kernelcache
kextcache -Boot -U /

kextcache updated critical boot files, requesting launchd reboot

but the problem is not resolved

**Comment by toleda** [comment]
Attach new files.

**Comment by maboloshi** [comment]
shamozhizideMac-mini:~ maboloshi$ /Users/maboloshi/Downloads/audio_cloverALC-120_v1.0a0.command 
 
Agreement
The audio_cloverALC-120 script is for personal use only. Do not distribute
the patch, any or all of the files or the resulting patched AppleHDA.kext
for any reason without permission. The audio_cloverALC-120 script is
provided as is and without any kind of warranty.
 
File: audio_cloverALC-120.command_v1.0a0
Release Mode
EFI partition is mounted
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

OK to patch
Confirm Realtek ALC892 (y/n): y
Clover Audio ID Injection (y/n): y
Use Audio ID: 1 (y/n): n
Audio IDs:
1 - 3/5/6 port Realtek ALCxxx audio
2 - 3 port (5.1) Realtek ALCxxx audio (n/a 885)
3 - HD3000/HD4000/HD5xx HDMI audio and Realtek ALCxxx audio (n/a 885 & 887/888 Legacy)
Select Audio ID: 3

Download ALC892 files ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25585  100 25585    0     0  27294      0 --:--:-- --:--:-- --:--:-- 27276
Edit config.plist/Devices/Audio/Inject/3
Edit config.plist/SystemParameters/InjectKexts/YES
Download kext patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1418  100  1418    0     0   2101      0 --:--:-- --:--:-- --:--:--  2100
Download config kext and install ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3665  100  3665    0     0   5460      0 --:--:-- --:--:-- --:--:--  5470
Install /Volumes/EFI/EFI/CLOVER/kexts/10.12/realtekALC.kext
Install System/Library/Extensions/AppleHDA.kext/ALC892 zml files
Fix permissions ...
Kernel cache...
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext RealtekRTL8111.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASRAID2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASHBA2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOCelerityFC8.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext HDAEnabler.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext LPCSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext GPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ACPISensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakeSMC.kext
kext-dev-mode allowing invalid signature -67054 0xFFFFFFFFFFFEFA12 for kext AppleHDA.kext
KernelCache ID: D24ECD1EE760700A0F62DCC0CE198DEE
kextcache updated critical boot files, requesting launchd reboot

Install finished, restart required.
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...
shamozhizideMac-mini:~ maboloshi$ 
  [恢复于 2016年8月7日 下午7:22:00]
Last login: Sun Aug  7 19:16:29 on console
Restored session: 2016年 8月 7日 星期日 19时10分05秒 CST
shamozhizideMac-mini:~ maboloshi$ 
  [恢复于 2016年8月7日 下午7:55:00]
Last login: Sun Aug  7 19:50:51 on console
Restored session: 2016年 8月 7日 星期日 19时26分13秒 CST
shamozhizideMac-mini:~ maboloshi$ sudo rm /System/Library/Caches/com.apple.kext.caches/Startup/kernelcache
Password:
shamozhizideMac-mini:~ maboloshi$ sudo kextcache -Boot -U /
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
VoodooHDA.kext has incorrect permissions; omitting.
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext RealtekRTL8111.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASRAID2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOExpressSASHBA2.kext
kext-dev-mode allowing invalid signature -67007 0xFFFFFFFFFFFEFA41 for kext ATTOCelerityFC8.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext LPCSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext GPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CPUSensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ACPISensors.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakeSMC.kext
kext-dev-mode allowing invalid signature -67054 0xFFFFFFFFFFFEFA12 for kext AppleHDA.kext
KernelCache ID: 7991A47C2EB6B31F93CD90CC2E8066F9
kextcache updated critical boot files, requesting launchd reboot
