### ISSUE TITLE
Having issues running the .command files.

### ISSUE THREAD

**Issue by hayhay7789** [toleda/audio_CloverALC#87]
Whenever I try to run one of the .command files, my Terminal says `cannot execute binary file` and does not run the command at all.

If it matters, after I download the file I do not have permissions to run it so I use `chmod u+x` to grant permissions to run it.

**Comment by toleda** [comment]
Where is the .command file located?

**Comment by hayhay7789** [comment]
I was messing it up - I was saving the downloads as a .command instead of a .zip.
