### ISSUE TITLE
Asus Z97-P with ALC81 issue

### ISSUE THREAD

**Issue by sajimon** [toleda/audio_CloverALC#90]
Hello, I have ASUS Z97-P with ALC891 (that is what online sources are telling me) I'm trying to apply audio_clover patches on el capitan. But I'am getting this output:

`./audio_cloverALC-120.sh 
 
Agreement
The audio_cloverALC script is for personal use only. Do not distribute
the patch, any or all of the files or the resulting patched AppleHDA.kext
for any reason without permission. The audio_cloverALC script is
provided as is and without any kind of warranty.
 
File: audio_cloverALC-120.command_v1.0d
Release Mode
Password:
EFI partition is mounted
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

OK to patch
Realtek ALC867 is not supported with audio_cloverALC-120.command_v1.0d
No system files were changed
To save a Copy of this Terminal session: Terminal/Shell/Export Text As ...`

Thing is, it's saying ALC867 is not supported, which I don't have...I'm confused.

**Comment by toleda** [comment]
ALC891 is renamed ALC867; not supported. See README.

**Comment by sajimon** [comment]
Sorry for late response. Here is my IOreg - and I want to add that i've found some examples of successful installations over the internet, here is an example https://www.reddit.com/r/hackintosh/comments/3g8msv/has_anyone_got_audio_working_on_the_asus_z97p_alc/

[ALC867.zip](https://github.com/toleda/audio_CloverALC/files/628051/ALC867.zip)

**Comment by sajimon** [comment]
@toleda Sorry to bother you again, but any updates on that issue? 
Thanks

**Comment by toleda** [comment]
Apologies, 
Disable SIP, mount EFI partition
Run ultiBeast 9+ > Drivers > Audio > RealtekALCxxx √ ALC887/888b

867 edits, see [audio_ALC867.zip](https://github.com/toleda/audio_CloverALC/files/671527/audio_ALC867.zip)

Restart
Attach edited AppleHDA.kext, config.plist. IOReg, Clover Bootlog.

**Comment by sajimon** [comment]
Hi @toleda  

I have followed every instruction best to my ability - I think I've done everything right. No sound tho. 
I'm attaching requested files.

Thanks
[887to867Applied.zip](https://github.com/toleda/audio_CloverALC/files/671733/887to867Applied.zip)

**Comment by toleda** [comment]
My mistake, install [AppleHDA.kext.zip](https://github.com/toleda/audio_CloverALC/files/671970/AppleHDA.kext.zip)
Verify Library/Extensions/realtekALC.kext is the same as attached above (zip files)
Remove EFI/CLOVER/kexts/10.12/realtekALC.kext
Reply with same files

**Comment by sajimon** [comment]
I've corrected it, still no success 😩 
Attaching new set of files, additionally I've thrown in /L/E/realtekALC.kext, it has passed my verification.

[887to867AppliedV2.zip](https://github.com/toleda/audio_CloverALC/files/672236/887to867AppliedV2.zip)

**Comment by sajimon** [comment]
I've also noticed there are some extra entries in Clover's "Kernel and Kext Patches" regarding AppleHDA, should that be?

**Comment by toleda** [comment]
3 AppleHDA patches, correct
Replace realtekALC with attached
Reply with new files
[realtekALC.kext.zip](https://github.com/toleda/audio_CloverALC/files/679809/realtekALC.kext.zip)

**Comment by sajimon** [comment]
@toleda Hi, replaced /L/E/realtekALC.kext with one you provided, unfortunately with no success.

[887to867AppliedV3.zip](https://github.com/toleda/audio_CloverALC/files/680003/887to867AppliedV3.zip)

**Comment by toleda** [comment]
Install attached files.
[v4.zip](https://github.com/toleda/audio_CloverALC/files/725576/v4.zip)
Reply with new files

**Comment by sajimon** [comment]
Hi, thanks for the update 👍 
Still not working :( 
I've changed files you provided in /S/E/L/AppleHDA.kext

I'm attaching files as usual.
[887to867AppliedV4.zip](https://github.com/toleda/audio_CloverALC/files/727291/887to867AppliedV4.zip)

**Comment by Idan1985** [comment]
Hello,
El Capitan needs the older version of the script - ALC110. 
ALC120 is for Sierra only. Search this thread and if you can't find it look in older hackintosh forum's or just google it... but I had the same problem... it's definitely it..

**Comment by toleda** [comment]
@sajimon: did you rename the new AppleHDA files from ... xml.zlip to ... zml.zlib when installed?

@Idan1985: not true. cloverALC-120 supports 10.8, 10.9, 10.10, 10.11, 10.12. cloverALC-110 does not support 10.12

**Comment by sajimon** [comment]
@toleda No, I didn't, should I?

I had both xml.zlib and zml.zlib in my AppleHDA.kext so I've just overwritten them (and Platforms.xml.zlib and zml.zlib variation). I think some of them are from first set of files you have sent me.
Maybe I should start from scratch with AppleHDA.kext patches to be sure everything is in correct place.

**Comment by toleda** [comment]
@sajimon
Yes. 
Use v5 files (file name updated) and previous instructions
[v5.zip](https://github.com/toleda/audio_CloverALC/files/737935/v5.zip)

**Comment by sajimon** [comment]
Done. 
What I did is just replaced given files in AppleHDA.kext/Resources as provided. Not changed any names.
No sound yet, but I think we are getting closer 😃 

[887to867AppliedV5.zip](https://github.com/toleda/audio_CloverALC/files/739410/887to867AppliedV5.zip)
