### ISSUE TITLE
ALC1150 10.12 shows devices, no sound (Similar to #78)

### ISSUE THREAD

**Issue by ajsinger1** [toleda/audio_CloverALC#99]
First off, I am new to to the world of hackintosh, and don't know 100% what I am doing. I read through all of the issues and found that in issue #78, I had the same error of:

KernelCache ID: C38E5387B7751823541CFECCBE8191C9
symlink("/System/Library/PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 17 (File exists)

Problem is, I have no clue what this means, or how to fix it. If someone could please help (With preferably step by step instructions) it would be much appreciated.

Thanks!

Here are some pictures

DPCI (Don't know what this is entirely but I saw others were posting it)
![screen shot 2017-02-25 at 5 44 40 pm](https://cloud.githubusercontent.com/assets/26032169/23335385/c4004a94-fb82-11e6-8de8-17c3edead367.png)

When I run the audio_cloverALC-120.command 
![screen shot 2017-02-25 at 5 45 37 pm](https://cloud.githubusercontent.com/assets/26032169/23335363/7254104a-fb82-11e6-81ca-fac865297767.png)

After reboot sound devices (Top 4 do not work, but I successfully did the HDMI audio guide)
![screen shot 2017-02-25 at 5 46 02 pm](https://cloud.githubusercontent.com/assets/26032169/23335370/8add0f4a-fb82-11e6-85e9-8c0536e64433.png)

Please Help!

**Comment by toleda** [comment]
Support only for cloverALC script.  AppleALC.kext uses same files and is incompatible with cloverALC. Decide what audio technique you want to work and remove the other.

**Comment by ajsinger1** [comment]
How do I find/remove AppleALC.kext? I can't find it anywhere.

**Comment by toleda** [comment]
No idea. Look in EFI/CLOVER/kexts/10.12 or other, S/L/E or L/E.

**Comment by ajsinger1** [comment]
Ok. I got rid of the AppleALC.kext (It was in S/L/E), reran the audio_cloverALC-120_v1.0d.command, rebooted, and it still didn't work.

If you can look at the bottom of the command when I ran it after removing the AppleALC.kext...
You can see everything looks OK until the end where it says 

symlink("/System/Library/PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 17 (File exists) <createPrelinkedKernel 2795>

![screen shot 2017-02-28 at 10 26 53 pm](https://cloud.githubusercontent.com/assets/26032169/23444821/5216d058-fe05-11e6-80a7-c4b884308312.png)

So... I dove into the /System/Library/Caches/com.apple.kext.caches/Startup folder, and found a plist file called loadedkextmt.plist
![screen shot 2017-02-28 at 10 26 23 pm](https://cloud.githubusercontent.com/assets/26032169/23444890/d5414c9c-fe05-11e6-80e9-fa7c163c211b.png)

I opened it up in TextWrangler and saw multiple AppleALC references:
![screen shot 2017-02-28 at 10 26 32 pm](https://cloud.githubusercontent.com/assets/26032169/23444895/dc3745b0-fe05-11e6-8821-a49799691d23.png)

I have a gut feeling I should be removing/editing some of this text, but I am worried to do anything without guidance. What should I do?

Thanks

**Comment by toleda** [comment]
See README/Problem Reporting, attach all request files.

**Comment by ahmadfiroz** [comment]
Can follow [This](https://www.reddit.com/r/hackintosh/comments/4sil5p/audio_mechanic_old_patchfix_removal_applealc/) link for audio removal (exept the applehda installation guide). 1150 applehda seems to have bug. ( my kernel panics ) then just run the cloveralc command

**Comment by toleda** [comment]
No 1150 bugs on my 1150.  Exactly, what is the problem with what?
